name: BrainstormOI
favicon: null
layout_spectrum: 0.616975128185004
typography_spectrum: 0.22776577714830637
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5506650272291154
  lightness: 0.44767623976804316
  saturation: 0.5037358682602644
  rhythmicContrast: 0.25145826558582485
purpose: []
